/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as NovaRouteImport } from './routes/nova'
import { Route as ConhecimentoIdRouteImport } from './routes/conhecimento.$id'
import { Route as ConversaIdRouteImport } from './routes/conversa.$id'
import { Route as CriarIndexRouteImport } from './routes/criar.index'
import { Route as CriarDescreverRouteImport } from './routes/criar.descrever'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRoute = NovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoIdRoute = ConhecimentoIdRouteImport.update({
  id: '/conhecimento/$id',
  path: '/conhecimento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversaIdRoute = ConversaIdRouteImport.update({
  id: '/conversa/$id',
  path: '/conversa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarIndexRoute = CriarIndexRouteImport.update({
  id: '/criar/',
  path: '/criar/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarDescreverRoute = CriarDescreverRouteImport.update({
  id: '/criar/descrever',
  path: '/criar/descrever',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/nova': typeof NovaRoute
  '/conhecimento/$id': typeof ConhecimentoIdRoute
  '/conversa/$id': typeof ConversaIdRoute
  '/criar/descrever': typeof CriarDescreverRoute
  '/criar/': typeof CriarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/nova': typeof NovaRoute
  '/conhecimento/$id': typeof ConhecimentoIdRoute
  '/conversa/$id': typeof ConversaIdRoute
  '/criar/descrever': typeof CriarDescreverRoute
  '/criar': typeof CriarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/explorar': typeof ExplorarRoute
  '/nova': typeof NovaRoute
  '/conhecimento/$id': typeof ConhecimentoIdRoute
  '/conversa/$id': typeof ConversaIdRoute
  '/criar/descrever': typeof CriarDescreverRoute
  '/criar/': typeof CriarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/explorar'
    | '/nova'
    | '/conhecimento/$id'
    | '/conversa/$id'
    | '/criar/descrever'
    | '/criar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/explorar'
    | '/nova'
    | '/conhecimento/$id'
    | '/conversa/$id'
    | '/criar/descrever'
    | '/criar'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/explorar'
    | '/nova'
    | '/conhecimento/$id'
    | '/conversa/$id'
    | '/criar/descrever'
    | '/criar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  ExplorarRoute: typeof ExplorarRoute
  NovaRoute: typeof NovaRoute
  ConhecimentoIdRoute: typeof ConhecimentoIdRoute
  ConversaIdRoute: typeof ConversaIdRoute
  CriarDescreverRoute: typeof CriarDescreverRoute
  CriarIndexRoute: typeof CriarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova': {
      id: '/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof NovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento/$id': {
      id: '/conhecimento/$id'
      path: '/conhecimento/$id'
      fullPath: '/conhecimento/$id'
      preLoaderRoute: typeof ConhecimentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversa/$id': {
      id: '/conversa/$id'
      path: '/conversa/$id'
      fullPath: '/conversa/$id'
      preLoaderRoute: typeof ConversaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/': {
      id: '/criar/'
      path: '/criar'
      fullPath: '/criar/'
      preLoaderRoute: typeof CriarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/descrever': {
      id: '/criar/descrever'
      path: '/criar/descrever'
      fullPath: '/criar/descrever'
      preLoaderRoute: typeof CriarDescreverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  ExplorarRoute: ExplorarRoute,
  NovaRoute: NovaRoute,
  ConhecimentoIdRoute: ConhecimentoIdRoute,
  ConversaIdRoute: ConversaIdRoute,
  CriarDescreverRoute: CriarDescreverRoute,
  CriarIndexRoute: CriarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
