/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoasVindasRouteImport } from './routes/boas-vindas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExcluirContaRouteImport } from './routes/excluir-conta'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ConversaIdRouteImport } from './routes/conversa.$id'
import { Route as CriarIndexRouteImport } from './routes/criar.index'
import { Route as CriarDescreverRouteImport } from './routes/criar.descrever'
import { Route as CriarPreparandoRouteImport } from './routes/criar.preparando'
import { Route as GuiaIdIndexRouteImport } from './routes/guia.$id.index'
import { Route as GuiaIdEditarRouteImport } from './routes/guia.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoasVindasRoute = BoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcluirContaRoute = ExcluirContaRouteImport.update({
  id: '/excluir-conta',
  path: '/excluir-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversaIdRoute = ConversaIdRouteImport.update({
  id: '/conversa/$id',
  path: '/conversa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarIndexRoute = CriarIndexRouteImport.update({
  id: '/criar/',
  path: '/criar/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarDescreverRoute = CriarDescreverRouteImport.update({
  id: '/criar/descrever',
  path: '/criar/descrever',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarPreparandoRoute = CriarPreparandoRouteImport.update({
  id: '/criar/preparando',
  path: '/criar/preparando',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaIdIndexRoute = GuiaIdIndexRouteImport.update({
  id: '/guia/$id/',
  path: '/guia/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaIdEditarRoute = GuiaIdEditarRouteImport.update({
  id: '/guia/$id/editar',
  path: '/guia/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entrar': typeof EntrarRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/explorar': typeof ExplorarRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/conversa/$id': typeof ConversaIdRoute
  '/criar/descrever': typeof CriarDescreverRoute
  '/criar/preparando': typeof CriarPreparandoRoute
  '/criar/': typeof CriarIndexRoute
  '/guia/$id/editar': typeof GuiaIdEditarRoute
  '/guia/$id/': typeof GuiaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entrar': typeof EntrarRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/explorar': typeof ExplorarRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/conversa/$id': typeof ConversaIdRoute
  '/criar/descrever': typeof CriarDescreverRoute
  '/criar/preparando': typeof CriarPreparandoRoute
  '/criar': typeof CriarIndexRoute
  '/guia/$id/editar': typeof GuiaIdEditarRoute
  '/guia/$id': typeof GuiaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entrar': typeof EntrarRoute
  '/excluir-conta': typeof ExcluirContaRoute
  '/explorar': typeof ExplorarRoute
  '/perfil': typeof PerfilRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/conversa/$id': typeof ConversaIdRoute
  '/criar/descrever': typeof CriarDescreverRoute
  '/criar/preparando': typeof CriarPreparandoRoute
  '/criar/': typeof CriarIndexRoute
  '/guia/$id/editar': typeof GuiaIdEditarRoute
  '/guia/$id/': typeof GuiaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boas-vindas'
    | '/configuracoes'
    | '/entrar'
    | '/excluir-conta'
    | '/explorar'
    | '/perfil'
    | '/privacidade'
    | '/termos'
    | '/conversa/$id'
    | '/criar/descrever'
    | '/criar/preparando'
    | '/criar/'
    | '/guia/$id/editar'
    | '/guia/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boas-vindas'
    | '/configuracoes'
    | '/entrar'
    | '/excluir-conta'
    | '/explorar'
    | '/perfil'
    | '/privacidade'
    | '/termos'
    | '/conversa/$id'
    | '/criar/descrever'
    | '/criar/preparando'
    | '/criar'
    | '/guia/$id/editar'
    | '/guia/$id'
  id:
    | '__root__'
    | '/'
    | '/boas-vindas'
    | '/configuracoes'
    | '/entrar'
    | '/excluir-conta'
    | '/explorar'
    | '/perfil'
    | '/privacidade'
    | '/termos'
    | '/conversa/$id'
    | '/criar/descrever'
    | '/criar/preparando'
    | '/criar/'
    | '/guia/$id/editar'
    | '/guia/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoasVindasRoute: typeof BoasVindasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EntrarRoute: typeof EntrarRoute
  ExcluirContaRoute: typeof ExcluirContaRoute
  ExplorarRoute: typeof ExplorarRoute
  PerfilRoute: typeof PerfilRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ConversaIdRoute: typeof ConversaIdRoute
  CriarDescreverRoute: typeof CriarDescreverRoute
  CriarPreparandoRoute: typeof CriarPreparandoRoute
  CriarIndexRoute: typeof CriarIndexRoute
  GuiaIdEditarRoute: typeof GuiaIdEditarRoute
  GuiaIdIndexRoute: typeof GuiaIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boas-vindas': {
      id: '/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof BoasVindasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excluir-conta': {
      id: '/excluir-conta'
      path: '/excluir-conta'
      fullPath: '/excluir-conta'
      preLoaderRoute: typeof ExcluirContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversa/$id': {
      id: '/conversa/$id'
      path: '/conversa/$id'
      fullPath: '/conversa/$id'
      preLoaderRoute: typeof ConversaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/': {
      id: '/criar/'
      path: '/criar'
      fullPath: '/criar/'
      preLoaderRoute: typeof CriarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/descrever': {
      id: '/criar/descrever'
      path: '/criar/descrever'
      fullPath: '/criar/descrever'
      preLoaderRoute: typeof CriarDescreverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar/preparando': {
      id: '/criar/preparando'
      path: '/criar/preparando'
      fullPath: '/criar/preparando'
      preLoaderRoute: typeof CriarPreparandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/$id/': {
      id: '/guia/$id/'
      path: '/guia/$id'
      fullPath: '/guia/$id/'
      preLoaderRoute: typeof GuiaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia/$id/editar': {
      id: '/guia/$id/editar'
      path: '/guia/$id/editar'
      fullPath: '/guia/$id/editar'
      preLoaderRoute: typeof GuiaIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoasVindasRoute: BoasVindasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EntrarRoute: EntrarRoute,
  ExcluirContaRoute: ExcluirContaRoute,
  ExplorarRoute: ExplorarRoute,
  PerfilRoute: PerfilRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ConversaIdRoute: ConversaIdRoute,
  CriarDescreverRoute: CriarDescreverRoute,
  CriarPreparandoRoute: CriarPreparandoRoute,
  CriarIndexRoute: CriarIndexRoute,
  GuiaIdEditarRoute: GuiaIdEditarRoute,
  GuiaIdIndexRoute: GuiaIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
